name: eye_vision
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  splashscreen: ^1.3.5
  splash_screen_view: ^3.0.0
  bottom_animation: ^2.0.0
  bottom_navy_bar: ^6.0.0
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  provider: ^6.0.1
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  firebase_analytics: ^8.3.4
  google_sign_in: ^5.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Arvo
      fonts:
        - asset: Fonts/Arvo-Bold.ttf
    - family: Playfair Display SC
      fonts:
        - asset: Fonts/PlayfairDisplaySC-Black.ttf
    - family: Open Sans Condensed
      fonts:
        - asset: Fonts/OpenSansCondensed-Bold.ttf
  assets:
    - assets/images/
    - assets/data/
